### PR TITLE
feat: let roo_url support multilingual

### PR DESCRIPTION
**Pull request by run26kimo**
This pull request will fix 
Before
http://127.0.0.1/e/en/

After
http://127.0.0.1/en/

### CODE REVIEW

**Comment by necojackarc** [comment]
Excuse me for the late reply.
This PR hadn't had any reviewers and assignees, so Github didn't notify me.
Anyway, thank you for reporting an issue and making a PR to fix that issue.

As far as I can see, this issue is caused by `url_for`, which is under the control of `default_url_options`.
Did you possibly set the locale option using `default_url_options`? Right?
Plus, the two methods we internally use are both affected by the options.

Then, I've made another PR to fix this issue. #3 
After merging that PR and releasing a new version, could you check it if it's fixed?

Thanks!

**Comment by necojackarc** [comment]
@run26kimo 
Excuse me for the late reply.
This PR hadn't had any reviewers and assignees, so Github didn't notify me.
Anyway, thank you for reporting an issue and making a PR to fix that issue.

As far as I can see, this issue is caused by url_for, which is under the control of default_url_options.
Did you possibly set the locale option using default_url_options? Right?
Plus, the two methods we internally use are both affected by the options.

Then, I've made another PR to fix this issue. #3
After merging that PR and releasing a new version, could you check it if it's fixed?

Thanks!

**Comment by yasaichi** [comment]
@necojackarc 
Probably @run26kimo puts `root to: ...` into `scope` in `routes.rb` as follows, not specifies `default_url_options`:

```ruby
Rails.application.routes.draw do
  scope "/:locale", locale: /en|nl/, defaults: { locale: "en" } do
    root to: "foo#bar"
  end
end
```

In this case, `@context.root_url` returns "http://127.0.0.1/en", and `compute_path(element)` does "/en" (we assume that `element` has been initialized with `root_path`).
So `"#{@context.root_url.chop}#{compute_path(element)}"` is "http://127.0.0.1/e/en/".

**Comment by necojackarc** [comment]
@yasaichi one question - is there any chance this case will happen?

```ruby
@root_url #=> https://foobar.com/en/
compute_path(element) #=> /en/item
```

**Comment by yasaichi** [comment]
@necojackarc 
> there any chance this case will happen?

Probably there is no chance of the above.
As far as I looked over the code of Rails, it strips off trailing slash and ensures there is a leading slash by `Journey::Router::Utils.normalize_path`, when registering the routes defined in `config/routes.rb`.
So `@context.root_url` should return two types of URL: "https://foobar.com/en" or "https://foobar.com/".

**Comment by necojackarc** [comment]
@yasaichi cool, thanks. then I'll adopt your suggestion. that's perfect for our case!

**Comment by necojackarc** [comment]
@yasaichi I've updated #3. please take a look if you have a chance. thanks!

**Comment by necojackarc** [comment]
@run26kimo
I justed released the new version, v1.0.1, which contains the changes in #3 that would fix this issue.
Then, I believe now everything is fine, so I'm closing this PR. Thank you!

**Comment by run26kimo** [comment]
Thank you guys

**Pull request closed without merging**
